/* eslint-disable @typescript-eslint/no-magic-numbers */
const MILLISECONDS_IN_ONE_SECOND = 1000
const SECONDS_IN_ONE_MINUTE = 60
const MINUTES_IN_ONE_HOUR = 60

const MILLISECONDS_IN_ONE_MINUTE = MILLISECONDS_IN_ONE_SECOND * SECONDS_IN_ONE_MINUTE
const MILLISECONDS_IN_ONE_HOUR = MILLISECONDS_IN_ONE_MINUTE * MINUTES_IN_ONE_HOUR

export const time = {
  MILLISECONDS_IN_ONE_SECOND: MILLISECONDS_IN_ONE_SECOND,
  SECONDS_IN_ONE_MINUTE: SECONDS_IN_ONE_MINUTE,
  MINUTES_IN_ONE_HOUR: MINUTES_IN_ONE_HOUR,
  MILLISECONDS_IN_ONE_MINUTE: MILLISECONDS_IN_ONE_MINUTE,
  MILLISECONDS_IN_ONE_HOUR: MILLISECONDS_IN_ONE_HOUR,
} as const
