const runtimeInformation = {
  STARTING_CHAT_BOT: 'Starting chatbot',
  CREATING_BOT: 'Creating bot',
  INITIALIZING_BOT_COMMANDS: 'Initializing bot commands',
  GOT_NEW_EVENT: 'Got new event',
  GOT_NEW_MESSAGE: 'Got message',
  NEW_HISTORY_RECORD: 'Creating new history record',
  NEW_BOT_EVENT_HANDLER: 'Creating new bot event handler',
  EXECUTING_COMMAND: 'Executing command',
  SENDING_MESSAGE: 'Sending message',
  DONE: 'Done',
  USER_MESSAGE_HANDLING: 'User message handling',
  GETTING_CHAT_ID: 'Getting chat ID',
  CALL_NEXT_HANDLER: 'Calling next handler',
  MESSAGE_TO_COMMAND_CONVERT: 'Message to command convertation',
  NO_LOCATION_IN_HANDLER: 'No location in handler',
  GETTING_USERNAME: 'Getting username',
  CAN_NOT_HANDLE_CALL_SUPER: 'Can not handle call super',
  FORMATTED_API_ENDPOINT: 'Formatted API endpoint:',
  CREATING_KEYBOARD_BUTTONS: 'Creating keyboard buttons',
  CONNECTING_TO_DATABASE: 'Connecting to the database',
  DISCONNECTING_FROM_DATABASE: 'Disconnecting from the database',
  SUBSCRIBING_USER: 'Subscribing user with telegramID:',
  UNSUBSCRIBING_USER: 'Unsubscribing user with telegramID:',
  GETTING_SUBSCRIPTION: 'Getting subscription for user with telegramID:',
  GETTING_USER_TELEGRAM_ID: 'Getting user with telegramID:',
  SETTING_ACTIVE_USER_TRACK: 'Setting active user track',
  RESETTING_TRACK_DOWN_TIMER: 'Resetting track down timer',
  USER_IS_ACTIVE_USER: 'User is active user',
  USER_ALREADY_SUBSCRIBED: 'User already subscribed',
  SENDING_NOTIFICATION: 'Sending notification',
  SETTING_USER_TIMEZONE: 'Setting user timezone',
  CREATING_KEYBOARD: 'Creating keyboard',
  KEYBOARD_CREATED: 'Keyboard created',
  KEYBOARD_ALREADY_CREATED: 'Keyboard already created',
  TRACKDOWN_TIMER_EXPIRED: 'Trackdown timer expired',
  CACHE_TTL_TIMER_EXPIRED: 'Cache TTL time expired',
  ADDING_USER_TO_CACHE: 'Adding user to cache',
  LOADED_USER_LIST_FROM_DB: 'Loaded user list from database',
  USER_LIST_LOADED_SUCCESSFULLY: 'User list loaded successfully',
  FETCHING_ALL_USER_NAMES_FROM_DB: 'Fetching all user names from database',
  FETCHING_ALL_USERS_FROM_DB: 'Fetching all users from database',
  UPDATING_USER_LOCATION: 'Updating user location',
  UPDATING_USER_NOTIFICATION_TIME: 'Updating user notification time',
  USER_NOTIFICATION_SCHEDULED_ON_NEW_TIME: 'User notification scheduled on new time',
} as const

export default runtimeInformation
